=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = FrontApi::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(FrontApi::AccountsApi)
    end
  end

  # unit tests for add_contact_to_account
  # Add contact to Account
  # Adds a list of contacts to an Account
  # @param account_id The Account ID. Alternatively, you can supply the account domain or external ID as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [ContactIds] :contact_ids 
  # @return [nil]
  describe 'add_contact_to_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_account
  # Create account
  # Create a new account.
  # @param [Hash] opts the optional parameters
  # @option opts [Account] :account 
  # @return [AccountResponse]
  describe 'create_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_an_account
  # Delete an account
  # Deletes an account
  # @param account_id The Account ID. Alternatively, you can supply the account domain or external ID as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_an_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for fetch_an_account
  # Fetch an account
  # Fetches an account
  # @param account_id The Account ID. Alternatively, you can supply the account domain or external ID as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @return [AccountResponse]
  describe 'fetch_an_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_account_contacts
  # List account contacts
  # Lists the contacts associated with an Account
  # @param account_id The Account ID. Alternatively, you can supply the account domain or external ID as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :sort_by Field used to sort the contacts. Either &#x60;created_at&#x60; or &#x60;updated_at&#x60;.
  # @option opts [String] :sort_order Order by which results should be sorted
  # @return [ListAccountContacts200Response]
  describe 'list_account_contacts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_accounts
  # List Accounts
  # List the accounts of the company.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :sort_by Field used to sort the accounts. Either &#x60;created_at&#x60; or &#x60;updated_at&#x60;.
  # @option opts [String] :sort_order Order by which results should be sorted
  # @return [ListAccounts200Response]
  describe 'list_accounts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_contact_from_account
  # Remove contact from Account
  # Removes a list of contacts from an Account
  # @param account_id The Account ID. Alternatively, you can supply the account domain or external ID as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [ContactIds] :contact_ids 
  # @return [nil]
  describe 'remove_contact_from_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_account
  # Update account
  # Updates an account.
  # @param account_id The Account ID. Alternatively, you can supply the account domain or external ID as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [AccountPatch] :account_patch 
  # @return [AccountResponse]
  describe 'update_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
