=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::AttachmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AttachmentsApi' do
  before do
    # run before each test
    @api_instance = FrontApi::AttachmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AttachmentsApi' do
    it 'should create an instance of AttachmentsApi' do
      expect(@api_instance).to be_instance_of(FrontApi::AttachmentsApi)
    end
  end

  # unit tests for download_attachment
  # Download attachment
  # Download an attachment file.
  # @param attachment_link_id The Attachment ID
  # @param [Hash] opts the optional parameters
  # @return [Attachment]
  describe 'download_attachment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
