=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::ChannelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ChannelsApi' do
  before do
    # run before each test
    @api_instance = FrontApi::ChannelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChannelsApi' do
    it 'should create an instance of ChannelsApi' do
      expect(@api_instance).to be_instance_of(FrontApi::ChannelsApi)
    end
  end

  # unit tests for create_a_channel
  # Create a channel
  # Create a channel in an inbox.
  # @param inbox_id The Inbox ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateChannel] :create_channel Channel to create
  # @return [nil]
  describe 'create_a_channel test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_channel
  # Get channel
  # Fetch a channel.
  # @param channel_id The Channel ID. Alternatively, you can supply the channel address as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @return [ChannelResponse]
  describe 'get_channel test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_channels
  # List channels
  # List the channels of the company.
  # @param [Hash] opts the optional parameters
  # @return [ListChannels200Response]
  describe 'list_channels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_team_channels
  # List team channels
  # List the channels of a team (workspace).
  # @param team_id The team ID
  # @param [Hash] opts the optional parameters
  # @return [ListChannels200Response]
  describe 'list_team_channels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_teammate_channels
  # List teammate channels
  # List the channels of a teammate.
  # @param teammate_id The teammate ID. Alternatively, you can supply an email as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @return [ListChannels200Response]
  describe 'list_teammate_channels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_channel
  # Update Channel
  # Update a channel.
  # @param channel_id The Channel ID. Alternatively, you can supply the channel address as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateChannel] :update_channel Channel details
  # @return [nil]
  describe 'update_channel test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for validate_channel
  # Validate channel
  # Asynchronously validate an SMTP channel (this endpoint is irrelevant to other channel types). When you create an SMTP channel via the API, [create a channel](https://dev.frontapp.com/reference/post_inboxes-inbox-id-channels) with type smtp and the send_as set to the needed email address. You then [configure the email provider](https://help.front.com/en/articles/2081), after which you use this endpoint to asynchronously validate the SMTP settings.
  # @param channel_id The Channel ID. Alternatively, you can supply the channel address as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @return [ValidateChannel202Response]
  describe 'validate_channel test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
