=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::ContactHandlesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContactHandlesApi' do
  before do
    # run before each test
    @api_instance = FrontApi::ContactHandlesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactHandlesApi' do
    it 'should create an instance of ContactHandlesApi' do
      expect(@api_instance).to be_instance_of(FrontApi::ContactHandlesApi)
    end
  end

  # unit tests for add_contact_handle
  # Add contact handle
  # Adds a new handle to a contact.
  # @param contact_id The contact ID. Alternatively, you can supply the contact&#39;s source and handle as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [ContactHandle] :contact_handle 
  # @return [nil]
  describe 'add_contact_handle test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_contact_handle
  # Delete contact handle
  # Remove a handle from a contact.
  # @param contact_id The contact ID. Alternatively, you can supply the contact&#39;s source and handle as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [DeleteContactHandle] :delete_contact_handle 
  # @return [nil]
  describe 'delete_contact_handle test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
