=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::KnowledgeBaseCategoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KnowledgeBaseCategoriesApi' do
  before do
    # run before each test
    @api_instance = FrontApi::KnowledgeBaseCategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KnowledgeBaseCategoriesApi' do
    it 'should create an instance of KnowledgeBaseCategoriesApi' do
      expect(@api_instance).to be_instance_of(FrontApi::KnowledgeBaseCategoriesApi)
    end
  end

  # unit tests for delete_a_knowledge_base_category
  # Delete a knowledge base category
  # Deletes a knowledge base category.  &gt; ⚠️ Warning &gt; &gt; When a category is deleted, all articles in the category are also deleted.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param category_id The ID of the category to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_a_knowledge_base_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_a_knowledge_base_category
  # Get a knowledge base category
  # Fetches a knowledge base category.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param category_id The ID of the category to fetch
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseCategorySlimResponse]
  describe 'get_a_knowledge_base_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_knowledge_base_category_content_in_default_locale
  # Get knowledge base category content in default locale
  # Fetches a knowledge base category with content in the default locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param category_id The ID of the category to fetch
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseCategoryResponse]
  describe 'get_knowledge_base_category_content_in_default_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_knowledge_base_category_with_content_in_specified_locale
  # Get knowledge base category with content in specified locale
  # Fetches a knowledge base category with content for a given locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param category_id The ID of the category to fetch
  # @param locale The [locale](https://dev.frontapp.com/reference/knowledge-bases#locales) of the content to fetch
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseCategoryResponse]
  describe 'get_knowledge_base_category_with_content_in_specified_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_categories_in_a_knowledge_base
  # List categories in a knowledge base
  # List categories in a knowledge base.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @return [ListCategoriesInAKnowledgeBase200Response]
  describe 'list_categories_in_a_knowledge_base test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_knowledge_base_category_in_default_locale
  # Update knowledge base category in default locale
  # Updates a knowledge base category in the default locale. Will republish the knowledge base if the knowledge base is currently published.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param category_id The ID of the category to update
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBaseCategoryPatch] :knowledge_base_category_patch 
  # @return [KnowledgeBaseCategoryResponse]
  describe 'update_knowledge_base_category_in_default_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_knowledge_base_category_in_specified_locale
  # Update knowledge base category in specified locale
  # Updates a knowledge base category for a given locale. Will republish the knowledge base if the knowledge base is currently published.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param category_id The ID of the category to update
  # @param locale The [locale](https://dev.frontapp.com/reference/knowledge-bases#locales) of the updated content
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBaseCategoryPatch] :knowledge_base_category_patch 
  # @return [KnowledgeBaseCategoryResponse]
  describe 'update_knowledge_base_category_in_specified_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
