=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::KnowledgeBaseArticlesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KnowledgeBaseArticlesApi' do
  before do
    # run before each test
    @api_instance = FrontApi::KnowledgeBaseArticlesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KnowledgeBaseArticlesApi' do
    it 'should create an instance of KnowledgeBaseArticlesApi' do
      expect(@api_instance).to be_instance_of(FrontApi::KnowledgeBaseArticlesApi)
    end
  end

  # unit tests for delete_an_article
  # Delete an article
  # Deletes an article and all its content and translations.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param article_id The ID of the article to delete
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseArticleSlimResponse]
  describe 'delete_an_article test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for download_attachment_from_an_article
  # Download attachment from an article
  # Downloads the attachment from an article.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param article_id The ID of the article
  # @param attachment_id The ID of the file to download
  # @param [Hash] opts the optional parameters
  # @return [Attachment]
  describe 'download_attachment_from_an_article test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_a_knowledge_base_article
  # Get a knowledge base article
  # Fetches a knowledge base article.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param article_id The ID of the article to fetch
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseArticleSlimResponse]
  describe 'get_a_knowledge_base_article test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_knowledge_base_article_with_content_in_default_locale
  # Get knowledge base article with content in default locale
  # Fetches a knowledge base article with content in the default locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param article_id The ID of the article to fetch
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseArticleResponse]
  describe 'get_knowledge_base_article_with_content_in_default_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_knowledge_base_article_with_content_in_specified_locale
  # Get knowledge base article with content in specified locale
  # Fetches a knowledge base article with content for a given locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param article_id The ID of the article to fetch
  # @param locale The [locale](https://dev.frontapp.com/reference/knowledge-bases#locales) of the content to fetch
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseArticleResponse]
  describe 'get_knowledge_base_article_with_content_in_specified_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_articles_in_a_category
  # List articles in a category
  # List articles in a category.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param category_id The ID of the category
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @return [ListArticlesInACategory200Response]
  describe 'list_articles_in_a_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_articles_in_a_knowledge_base
  # List articles in a knowledge base
  # List articles in a knowledge base  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @return [ListArticlesInACategory200Response]
  describe 'list_articles_in_a_knowledge_base test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_article_content_in_default_locale
  # Update article content in default locale.
  # Updates an article&#39;s content in the default locale  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param article_id The ID of the article to update
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBaseArticlePatch] :knowledge_base_article_patch 
  # @return [KnowledgeBaseArticleResponse]
  describe 'update_article_content_in_default_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_article_content_in_specified_locale
  # Update article content in specified locale
  # Updates an article&#39;s content for a given locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param article_id The ID of the article to update
  # @param locale The [locale](https://dev.frontapp.com/reference/knowledge-bases#locales) of the updated content
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBaseArticlePatch] :knowledge_base_article_patch 
  # @return [KnowledgeBaseArticleResponse]
  describe 'update_article_content_in_specified_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
