=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::KnowledgeBasesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KnowledgeBasesApi' do
  before do
    # run before each test
    @api_instance = FrontApi::KnowledgeBasesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KnowledgeBasesApi' do
    it 'should create an instance of KnowledgeBasesApi' do
      expect(@api_instance).to be_instance_of(FrontApi::KnowledgeBasesApi)
    end
  end

  # unit tests for create_a_knowledge_base
  # Create a knowledge base
  # Creates a knowledge base.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBaseCreate] :knowledge_base_create 
  # @return [KnowledgeBaseResponse]
  describe 'create_a_knowledge_base test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_article_in_a_knowledge_base_in_default_locale
  # Create article in a knowledge base in default locale
  # Creates an article in a knowledge base in the default locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base to create the article in
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBaseArticleCreate] :knowledge_base_article_create 
  # @return [KnowledgeBaseArticleResponse]
  describe 'create_article_in_a_knowledge_base_in_default_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_article_in_a_knowledge_base_in_specified_locale
  # Create article in a knowledge base in specified locale
  # Create an article for a given locale in a knowledge base.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base to create the article in
  # @param locale The [locale](https://dev.frontapp.com/reference/knowledge-bases#locales) of the article&#39;s content
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBaseArticleCreate] :knowledge_base_article_create 
  # @return [KnowledgeBaseArticleResponse]
  describe 'create_article_in_a_knowledge_base_in_specified_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_knowledge_base_category_in_default_locale
  # Create knowledge base category in default locale
  # Creates a knowledge base category in the default locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base to create the category in
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBaseCategoryCreate] :knowledge_base_category_create 
  # @return [KnowledgeBaseCategoryResponse]
  describe 'create_knowledge_base_category_in_default_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_knowledge_base_category_in_specified_locale
  # Create knowledge base category in specified locale
  # Creates a knowledge base category for a given locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base to create the category in
  # @param locale The [locale](https://dev.frontapp.com/reference/knowledge-bases#locales) of the category&#39;s content
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBaseCategoryCreate] :knowledge_base_category_create 
  # @return [KnowledgeBaseCategoryResponse]
  describe 'create_knowledge_base_category_in_specified_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_a_knowledge_base
  # Get a knowledge base
  # Fetches a knowledge base.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base to fetch
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseSlimResponse]
  describe 'get_a_knowledge_base test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_a_knowledge_base_with_content_in_default_locale
  # Get a knowledge base with content in default locale
  # Fetches a knowledge base with its content in the default locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base to fetch
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseResponse]
  describe 'get_a_knowledge_base_with_content_in_default_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_a_knowledge_base_with_content_in_specified_locale
  # Get a knowledge base with content in specified locale
  # Fetches a knowledge base with its content for a given locale.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base to fetch
  # @param locale The [locale](https://dev.frontapp.com/reference/knowledge-bases#locales) of the content to fetch
  # @param [Hash] opts the optional parameters
  # @return [KnowledgeBaseResponse]
  describe 'get_a_knowledge_base_with_content_in_specified_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_knowledge_bases
  # List knowledge bases
  # List the knowledge bases of the company.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param [Hash] opts the optional parameters
  # @return [ListKnowledgeBases200Response]
  describe 'list_knowledge_bases test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_knowledge_base_in_default_locale
  # Update knowledge base in default locale
  # Updates a knowledge base in the default locale. Will republish the knowledge base if the knowledge base is currently published.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base to update
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBasePatch] :knowledge_base_patch 
  # @return [KnowledgeBaseResponse]
  describe 'update_knowledge_base_in_default_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_knowledge_base_in_specified_locale
  # Update knowledge base in specified locale
  # Updates a knowledge base for a given locale. Will republish the knowledge base if the knowledge base is currently published.  **Note**: You must use an API token to authenticate. OAuth is not supported at this time. 
  # @param knowledge_base_id The ID of the knowledge base to update
  # @param locale The [locale](https://dev.frontapp.com/reference/knowledge-bases#locales) of the updated content
  # @param [Hash] opts the optional parameters
  # @option opts [KnowledgeBasePatch] :knowledge_base_patch 
  # @return [KnowledgeBaseResponse]
  describe 'update_knowledge_base_in_specified_locale test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
