=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::MessageTemplateFoldersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MessageTemplateFoldersApi' do
  before do
    # run before each test
    @api_instance = FrontApi::MessageTemplateFoldersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessageTemplateFoldersApi' do
    it 'should create an instance of MessageTemplateFoldersApi' do
      expect(@api_instance).to be_instance_of(FrontApi::MessageTemplateFoldersApi)
    end
  end

  # unit tests for create_child_folder
  # Create child folder
  # Create a new message template folder as a child of the given folder
  # @param message_template_folder_id The parent message template folder ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateMessageTemplateFolderAsChild] :create_message_template_folder_as_child Message template folder to create
  # @return [MessageTemplateFolderResponse]
  describe 'create_child_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_folder
  # Create folder
  # Create a new message template folder.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateMessageTemplateFolder] :create_message_template_folder Message template folder to create
  # @return [MessageTemplateFolderResponse]
  describe 'create_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_team_folder
  # Create team folder
  # Create a new message template folder belonging to the requested team (workspace).
  # @param team_id The team ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateMessageTemplateFolder] :create_message_template_folder Message template folder to create
  # @return [MessageTemplateFolderResponse]
  describe 'create_team_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_teammate_folder
  # Create teammate folder
  # Create a new message template folder belonging to the requested teammate.
  # @param teammate_id The teammate ID. Alternatively, you can supply an email as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [CreateMessageTemplateFolder] :create_message_template_folder Message template folder to create
  # @return [MessageTemplateFolderResponse]
  describe 'create_teammate_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_folder
  # Delete folder
  # Delete a message template folder and child folders/templates
  # @param message_template_folder_id The message template folder id
  # @param [Hash] opts the optional parameters
  # @return [DeleteFolder202Response]
  describe 'delete_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_child_folders
  # Get child folders
  # Fetch the child message templates folders of a message template folder.
  # @param message_template_folder_id The message template folder ID
  # @param [Hash] opts the optional parameters
  # @return [ListFolders200Response]
  describe 'get_child_folders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_folder
  # Get folder
  # Fetch a message template folder.
  # @param message_template_folder_id The message template folder ID
  # @param [Hash] opts the optional parameters
  # @return [MessageTemplateFolderResponse]
  describe 'get_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_folders
  # List folders
  # List the message template folders.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort_by Field used to sort the message template folders. Either &#x60;created_at&#x60; or &#x60;updated_at&#x60;.
  # @option opts [String] :sort_order Order by which results should be sorted
  # @return [ListFolders200Response]
  describe 'list_folders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_team_folders
  # List team folders
  # List the message template folders belonging to the requested team (workspace).
  # @param team_id The team ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort_by Field used to sort the message template folders. Either &#x60;created_at&#x60; or &#x60;updated_at&#x60;.
  # @option opts [String] :sort_order Order by which results should be sorted
  # @return [ListFolders200Response]
  describe 'list_team_folders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_teammate_folders
  # List teammate folders
  # List the message template folders belonging to the requested teammate.
  # @param teammate_id The teammate ID. Alternatively, you can supply an email as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort_by Field used to sort the message template folders. Either &#x60;created_at&#x60; or &#x60;updated_at&#x60;.
  # @option opts [String] :sort_order Order by which results should be sorted
  # @return [ListFolders200Response]
  describe 'list_teammate_folders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_folder
  # Update folder
  # Update message template folder
  # @param message_template_folder_id The message template folder ID
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateMessageTemplateFolder] :update_message_template_folder Message template folder to update
  # @return [MessageTemplateFolderResponse]
  describe 'update_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
