=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::TagsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TagsApi' do
  before do
    # run before each test
    @api_instance = FrontApi::TagsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TagsApi' do
    it 'should create an instance of TagsApi' do
      expect(@api_instance).to be_instance_of(FrontApi::TagsApi)
    end
  end

  # unit tests for create_child_tag
  # Create child tag
  # Creates a child tag.
  # @param tag_id The tag ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateTag] :create_tag Child Tag to create
  # @return [TagResponse]
  describe 'create_child_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_company_tag
  # Create company tag
  # Create a company tag.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateTag] :create_tag Tag to create
  # @return [TagResponse]
  describe 'create_company_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_tag
  # Create tag
  # Create a tag in the oldest team (workspace). This is a legacy endpoint. Use the Create company tag, Create team tag, or Create teammate tag endpoints instead.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateTag] :create_tag Tag to create
  # @return [TagResponse]
  describe 'create_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_team_tag
  # Create team tag
  # Create a tag for a team (workspace).
  # @param team_id The team ID
  # @param [Hash] opts the optional parameters
  # @option opts [CreateTag] :create_tag Tag to create
  # @return [TagResponse]
  describe 'create_team_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_teammate_tag
  # Create teammate tag
  # Create a tag for a teammate.
  # @param teammate_id The teammate ID. Alternatively, you can supply an email as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [CreateTag] :create_tag Tag to create
  # @return [TagResponse]
  describe 'create_teammate_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_tag
  # Delete tag
  # Delete a tag.
  # @param tag_id The ID of the tag to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_tag
  # Get tag
  # Fetch a tag.
  # @param tag_id The tag ID
  # @param [Hash] opts the optional parameters
  # @return [TagResponse]
  describe 'get_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_company_tags
  # List company tags
  # List the company tags.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :sort_by Field used to sort the tags. Only supports &#x60;id&#x60;.
  # @option opts [String] :sort_order Order by which results should be sorted
  # @return [ListCompanyTags200Response]
  describe 'list_company_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tag_children
  # List tag children
  # List the children of a specific tag.
  # @param tag_id The tag ID
  # @param [Hash] opts the optional parameters
  # @return [ListCompanyTags200Response]
  describe 'list_tag_children test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tagged_conversations
  # List tagged conversations
  # List the conversations tagged with a tag. For more advanced filtering, see the [search endpoint](https://dev.frontapp.com/reference/conversations#search-conversations). 
  # @param tag_id The ID of the tag
  # @param [Hash] opts the optional parameters
  # @option opts [String] :q [Search query object](https://dev.frontapp.com/docs/query-object-q) with a property &#x60;statuses&#x60;, whose value should be a list of conversation statuses (&#x60;assigned&#x60;, &#x60;unassigned&#x60;, &#x60;archived&#x60;, or &#x60;deleted&#x60;).
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @return [ListContactConversations200Response]
  describe 'list_tagged_conversations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tags
  # List tags
  # List all the tags of the company that the API token has access to, whether they be company tags, team tags, or teammate tags.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :sort_by Field used to sort the tags. Only supports &#x60;id&#x60;.
  # @option opts [String] :sort_order Order by which results should be sorted
  # @return [ListCompanyTags200Response]
  describe 'list_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_team_tags
  # List team tags
  # List the tags for a team (workspace).
  # @param team_id The team ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :sort_by Field used to sort the tags. Only supports &#x60;id&#x60;.
  # @option opts [String] :sort_order Order by which results should be sorted
  # @return [ListCompanyTags200Response]
  describe 'list_team_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_teammate_tags
  # List teammate tags
  # List the tags for a teammate.
  # @param teammate_id The teammate ID. Alternatively, you can supply an email as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :page_token Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
  # @option opts [String] :sort_by Field used to sort the tags. Only supports &#x60;id&#x60;.
  # @option opts [String] :sort_order Order by which results should be sorted
  # @return [ListCompanyTags200Response]
  describe 'list_teammate_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_a_tag
  # Update a tag
  # Update a tag.
  # @param tag_id The tag ID
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateTag] :update_tag Child Tag to update
  # @return [nil]
  describe 'update_a_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
