=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FrontApi::TeamsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TeamsApi' do
  before do
    # run before each test
    @api_instance = FrontApi::TeamsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeamsApi' do
    it 'should create an instance of TeamsApi' do
      expect(@api_instance).to be_instance_of(FrontApi::TeamsApi)
    end
  end

  # unit tests for add_teammates_to_team
  # Add teammates to team
  # Add one or more teammates to a team (workspace).
  # @param team_id The Team ID
  # @param [Hash] opts the optional parameters
  # @option opts [TeammateIds] :teammate_ids Teammate IDs to add. Alternatively, you can supply emails as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @return [nil]
  describe 'add_teammates_to_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_team
  # Get team
  # Fetch a team (workspace).
  # @param team_id The Team ID
  # @param [Hash] opts the optional parameters
  # @return [TeamResponse]
  describe 'get_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_teams
  # List teams
  # List the teams (workspaces) in the company.
  # @param [Hash] opts the optional parameters
  # @return [ListCompanyTeammateGroupTeams200Response]
  describe 'list_teams test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_teammates_from_team
  # Remove teammates from team
  # Remove one or more teammates from a team (workspace). Alternatively, you can supply emails as a [resource alias](https://dev.frontapp.com/docs/resource-aliases-1).
  # @param team_id The Team ID
  # @param [Hash] opts the optional parameters
  # @option opts [TeammateIds] :teammate_ids Teammate IDs to remove from the team
  # @return [nil]
  describe 'remove_teammates_from_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
