=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FrontApi::AnalyticsScalarType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FrontApi::AnalyticsScalarType do
  let(:instance) { FrontApi::AnalyticsScalarType.new }

  describe 'test an instance of AnalyticsScalarType' do
    it 'should create an instance of AnalyticsScalarType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FrontApi::AnalyticsScalarType)
    end
  end

end
