=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FrontApi::CustomFieldResponseLinks
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FrontApi::CustomFieldResponseLinks do
  let(:instance) { FrontApi::CustomFieldResponseLinks.new }

  describe 'test an instance of CustomFieldResponseLinks' do
    it 'should create an instance of CustomFieldResponseLinks' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FrontApi::CustomFieldResponseLinks)
    end
  end

  describe 'test attribute "_self"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
