=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FrontApi::KnowledgeBaseCategoryResponseLinksRelated
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FrontApi::KnowledgeBaseCategoryResponseLinksRelated do
  let(:instance) { FrontApi::KnowledgeBaseCategoryResponseLinksRelated.new }

  describe 'test an instance of KnowledgeBaseCategoryResponseLinksRelated' do
    it 'should create an instance of KnowledgeBaseCategoryResponseLinksRelated' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FrontApi::KnowledgeBaseCategoryResponseLinksRelated)
    end
  end

  describe 'test attribute "knowledge_base"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "parent_category"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "articles"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
