=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module FrontApi
  class AnalyticsMetricId
    AVG_CSAT_SURVEY_RESPONSE = "avg_csat_survey_response".freeze
    AVG_FIRST_RESPONSE_TIME = "avg_first_response_time".freeze
    AVG_HANDLE_TIME = "avg_handle_time".freeze
    AVG_REPLIES_TO_RESOLUTION = "avg_replies_to_resolution".freeze
    AVG_RESOLUTION_TIME = "avg_resolution_time".freeze
    AVG_RESPONSE_TIME = "avg_response_time".freeze
    AVG_SLA_BREACH_TIME = "avg_sla_breach_time".freeze
    AVG_TOTAL_REPLY_TIME = "avg_total_reply_time".freeze
    NEW_SEGMENTS_COUNT = "new_segments_count".freeze
    NUM_ACTIVE_SEGMENTS_FULL = "num_active_segments_full".freeze
    NUM_ARCHIVED_SEGMENTS = "num_archived_segments".freeze
    NUM_ARCHIVED_SEGMENTS_WITH_REPLY = "num_archived_segments_with_reply".freeze
    NUM_CSAT_SURVEY_RESPONSE = "num_csat_survey_response".freeze
    NUM_MESSAGES_RECEIVED = "num_messages_received".freeze
    NUM_MESSAGES_SENT = "num_messages_sent".freeze
    NUM_SLA_BREACH = "num_sla_breach".freeze
    PCT_CSAT_SURVEY_SATISFACTION = "pct_csat_survey_satisfaction".freeze
    PCT_RESOLVED_ON_FIRST_REPLY = "pct_resolved_on_first_reply".freeze
    PCT_TAGGED_CONVERSATIONS = "pct_tagged_conversations".freeze
    NUM_CLOSED_SEGMENTS = "num_closed_segments".freeze
    NUM_OPEN_SEGMENTS_START = "num_open_segments_start".freeze
    NUM_OPEN_SEGMENTS_END = "num_open_segments_end".freeze
    NUM_RESOLVED_SEGMENTS = "num_resolved_segments".freeze
    NUM_UNRESOLVED_ACTIVE_SEGMENTS = "num_unresolved_active_segments".freeze
    NUM_WORKLOAD_SEGMENTS = "num_workload_segments".freeze

    def self.all_vars
      @all_vars ||= [AVG_CSAT_SURVEY_RESPONSE, AVG_FIRST_RESPONSE_TIME, AVG_HANDLE_TIME, AVG_REPLIES_TO_RESOLUTION, AVG_RESOLUTION_TIME, AVG_RESPONSE_TIME, AVG_SLA_BREACH_TIME, AVG_TOTAL_REPLY_TIME, NEW_SEGMENTS_COUNT, NUM_ACTIVE_SEGMENTS_FULL, NUM_ARCHIVED_SEGMENTS, NUM_ARCHIVED_SEGMENTS_WITH_REPLY, NUM_CSAT_SURVEY_RESPONSE, NUM_MESSAGES_RECEIVED, NUM_MESSAGES_SENT, NUM_SLA_BREACH, PCT_CSAT_SURVEY_SATISFACTION, PCT_RESOLVED_ON_FIRST_REPLY, PCT_TAGGED_CONVERSATIONS, NUM_CLOSED_SEGMENTS, NUM_OPEN_SEGMENTS_START, NUM_OPEN_SEGMENTS_END, NUM_RESOLVED_SEGMENTS, NUM_UNRESOLVED_ACTIVE_SEGMENTS, NUM_WORKLOAD_SEGMENTS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AnalyticsMetricId.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AnalyticsMetricId"
    end
  end
end
