=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module FrontApi
  class AnalyticsScalarType
    NUMBER = "number".freeze
    PERCENTAGE = "percentage".freeze
    STRING = "string".freeze
    DURATION = "duration".freeze

    def self.all_vars
      @all_vars ||= [NUMBER, PERCENTAGE, STRING, DURATION].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AnalyticsScalarType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AnalyticsScalarType"
    end
  end
end
