=begin
#Core API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module FrontApi
  class AnalyticsActivitiesColumns
    ACTIVITY_ID = "Activity ID".freeze
    TYPE = "Type".freeze
    SOURCE = "Source".freeze
    MESSAGE_ID = "Message ID".freeze
    CONVERSATION_ID = "Conversation ID".freeze
    SEGMENT = "Segment".freeze
    SEGMENT_START = "Segment start".freeze
    SEGMENT_END = "Segment end".freeze
    DIRECTION = "Direction".freeze
    STATUS = "Status".freeze
    STATUS_AT_ACTIVITY_TIME = "Status at activity time".freeze
    INBOX = "Inbox".freeze
    INBOX_API_ID = "Inbox API ID".freeze
    INBOX_AT_ACTIVITY_TIME = "Inbox at activity time".freeze
    INBOX_API_IDS_AT_ACTIVITY_TIME = "Inbox API IDs at activity time".freeze
    PREVIOUS_INBOX_IDS = "Previous inbox IDs".freeze
    MESSAGE_DATE = "Message date".freeze
    AUTOREPLY = "Autoreply".freeze
    REACTION_TIME = "Reaction time".freeze
    TOTAL_REPLY_TIME = "Total reply time".freeze
    HANDLE_TIME = "Handle time".freeze
    RESPONSE_TIME = "Response time".freeze
    STAGE_RESOLUTION_TIME = "Stage resolution time".freeze
    REPLIES_TO_RESOLUTION = "Replies to resolution".freeze
    TICKET_RESOLUTION_TIME = "Ticket resolution time".freeze
    TICKET_REPLIES_TO_RESOLUTION = "Ticket replies to resolution".freeze
    ATTRIBUTED_TO = "Attributed to".freeze
    ASSIGNEE = "Assignee".freeze
    AUTHOR = "Author".freeze
    CONTACT_NAME = "Contact name".freeze
    CONTACT_HANDLE = "Contact handle".freeze
    ACCOUNT_NAMES = "Account names".freeze
    TO = "To".freeze
    CC = "Cc".freeze
    BCC = "Bcc".freeze
    EXTRACT = "Extract".freeze
    TAGS = "Tags".freeze
    TAG_API_IDS = "Tag API IDs".freeze
    TAGS_AT_ACTIVITY_TIME = "Tags at activity time".freeze
    TAG_API_IDS_AT_ACTIVITY_TIME = "Tag API IDs at activity time".freeze
    TAG_APPLICATION_DURATION = "Tag application duration".freeze
    ACTIVITY_API_ID = "Activity API ID".freeze
    MESSAGE_API_ID = "Message API ID".freeze
    COMMENT_API_ID = "Comment API ID".freeze
    CONVERSATION_API_ID = "Conversation API ID".freeze
    MESSAGE_ORIGINAL_ID = "Message original ID".freeze
    NEW_CONVERSATION = "New Conversation".freeze
    FIRST_RESPONSE = "First response".freeze
    BUSINESS_HOURS = "Business hours".freeze
    SUBJECT = "Subject".freeze
    ACCOUNT_NAME = "Account name".freeze
    SURVEY_RATING = "Survey rating".freeze
    SURVEY_COMMENT = "Survey comment".freeze
    SEGMENT_CLOSED = "Segment closed".freeze
    SEGMENT_CONTAINS_MESSAGES = "Segment contains messages".freeze
    LAST_SEGMENT_ACTIVITY = "Last segment activity".freeze
    ADDED_TAG = "Added tag".freeze
    ADDED_TAG_API_ID = "Added tag API ID".freeze
    REMOVED_TAG = "Removed tag".freeze
    REMOVED_TAG_API_ID = "Removed tag API ID".freeze
    SEGMENT_CUMULATIVE_TEAMMATES = "Segment cumulative teammates".freeze

    def self.all_vars
      @all_vars ||= [ACTIVITY_ID, TYPE, SOURCE, MESSAGE_ID, CONVERSATION_ID, SEGMENT, SEGMENT_START, SEGMENT_END, DIRECTION, STATUS, STATUS_AT_ACTIVITY_TIME, INBOX, INBOX_API_ID, INBOX_AT_ACTIVITY_TIME, INBOX_API_IDS_AT_ACTIVITY_TIME, PREVIOUS_INBOX_IDS, MESSAGE_DATE, AUTOREPLY, REACTION_TIME, TOTAL_REPLY_TIME, HANDLE_TIME, RESPONSE_TIME, STAGE_RESOLUTION_TIME, REPLIES_TO_RESOLUTION, TICKET_RESOLUTION_TIME, TICKET_REPLIES_TO_RESOLUTION, ATTRIBUTED_TO, ASSIGNEE, AUTHOR, CONTACT_NAME, CONTACT_HANDLE, ACCOUNT_NAMES, TO, CC, BCC, EXTRACT, TAGS, TAG_API_IDS, TAGS_AT_ACTIVITY_TIME, TAG_API_IDS_AT_ACTIVITY_TIME, TAG_APPLICATION_DURATION, ACTIVITY_API_ID, MESSAGE_API_ID, COMMENT_API_ID, CONVERSATION_API_ID, MESSAGE_ORIGINAL_ID, NEW_CONVERSATION, FIRST_RESPONSE, BUSINESS_HOURS, SUBJECT, ACCOUNT_NAME, SURVEY_RATING, SURVEY_COMMENT, SEGMENT_CLOSED, SEGMENT_CONTAINS_MESSAGES, LAST_SEGMENT_ACTIVITY, ADDED_TAG, ADDED_TAG_API_ID, REMOVED_TAG, REMOVED_TAG_API_ID, SEGMENT_CUMULATIVE_TEAMMATES].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AnalyticsActivitiesColumns.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AnalyticsActivitiesColumns"
    end
  end
end
